accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'


urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('page/<username>', views.PageView.as_view(), name='user-page'),
    path('edit', views.EditProfileView.as_view(), name='user-edit'),
    path('add-to-watched/<movie_id>', views.AddToWatched.as_view(), name='add-to-watched'),
    path('remove-from-watched/<movie_id>', views.RemoveFromWatched.as_view(), name='remove-from-watched'),
    path('remove-from-favs/<movie_id>', views.RemoveFromFavs.as_view(), name='remove-from-favs'),
    path('add-to-fav/<movie_id>', views.AddToFav.as_view(), name='add-to-fav'),
    path('search', views.FindPeopleView.as_view(), name='find-people'),
    path('add-to-requested/<username>', views.AddToRequested.as_view(), name='add-to-requested'),
    path('notification', views.NotificationView.as_view(), name='notification'),
    path('add-to-friends/<username>', views.AddToFriends.as_view(), name='add-to-friends'),
    path('reject/<username>', views.Reject.as_view(), name='reject'),
    path('suggest/<movie_id>', views.CreateSuggestView.as_view(), name='suggest'),
]

films/urls.py
from django.urls import path
from films import views

app_name = 'films'


urlpatterns = [
    path('search', views.SearchView.as_view(), name='search'),
    path('film-view/<movie_id>', views.FilmView.as_view(), name='film-view'),
    path('film-view/find-film/<movie_title>', views.FilmViewRedirector.as_view(), name='film-redirector'),
]

hobby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

from hobby import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('films/', include('films.urls', namespace='films'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    """
    Creates and saves a User with the given email, date of
    birth and password.
    """

    def create_user(self, username, name, password=""):
        username = username
        password = password
        name = name
        user = self.model(
            username=username,
            password=password,
            name=name
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username=username,
            password=password,
            name=name,
        )
        user.is_admin = True
        user.save()
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='avatars/', default='')
    bio = models.CharField(max_length=1000)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['password', 'name']

    objects = UserManager()

    # Hobby Fields:
    watched_films = models.ManyToManyField('films.Film', blank=True, related_name='watched')
    fav_list      = models.ManyToManyField('films.Film', blank=True, related_name='fav')
    last_watched_film = models.ForeignKey('films.Film', on_delete=models.CASCADE, blank=True, related_name='lastWatched', null=True)
    requested_users = models.ManyToManyField('accounts.User', related_name='request_users', blank=True, null=True)
    friends = models.ManyToManyField('accounts.User', related_name='friends_users', blank=True, null=True)
    suggests = models.ManyToManyField('films.Suggest', related_name='suggests', null=True, blank=True)

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Comment(models.Model):
    text = models.CharField(max_length=1000)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.writer.username + " : " + self.text[:20]

accounts/forms.py
from django import forms

from accounts.models import User


class SighUpForm(forms.Form):
    username = forms.CharField(max_length=50)
    password1 = forms.CharField(widget=forms.PasswordInput(), label='password')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='password confirm')
    full_name = forms.CharField(max_length=100)


    def save(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password1']
        name     = self.cleaned_data['name']
        user = User.objects.create(
            username=username,
            password=password,
            name=name)
        user.set_password(password)
        user.save()


class CommentForm(forms.Form):
    text = forms.CharField()

accounts/views.py
from django.conf import settings
from django.contrib.auth import logout, login
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import FormView, DetailView, RedirectView, CreateView, TemplateView, ListView
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import FormMixin

from accounts.forms import SighUpForm
from accounts.models import User
from films.models import Film
from hobby import urls


class SignUpView(FormView):
    def get(self, request, *args, **kwargs):
        form = SighUpForm()

        return render(request, 'accounts/signup.html', {'form':form})

    def post(self, request, *args, **kwargs):
        form = SighUpForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['password1'] == form.cleaned_data['password2']:
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                name = form.cleaned_data['full_name']
                user = User.objects.create(
                    username=username,
                    password=password,
                    name=name)
                user.set_password(password)
                user.save()
                return HttpResponseRedirect(reverse_lazy('accounts:login'))

        return HttpResponseRedirect(reverse_lazy('home'))


class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        login(self.request, form.get_user())

        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class AddToWatched(RedirectView):

    def get(self, request, *args, **kwargs):
        movie_id = self.kwargs['movie_id']
        film = Film.objects.get(imdbId=movie_id)
        self.request.user.watched_films.add(film)
        self.request.user.save()
        return super(AddToWatched, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('films:film-view', kwargs={'movie_id': self.kwargs['movie_id']})



class AddToFav(RedirectView):
    url = reverse_lazy('accounts:profile')

    def get(self, request, *args, **kwargs):
        movie_id = self.kwargs['movie_id']
        film = Film.objects.get(imdbId=movie_id)
        self.request.user.fav_list.add(film)
        self.request.user.save()
        return super(AddToFav, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('films:film-view', kwargs={'movie_id': self.kwargs['movie_id']})



class RemoveFromWatched(RedirectView):

    def get(self, request, *args, **kwargs):
        movie_id = self.kwargs['movie_id']
        film = Film.objects.get(imdbId=movie_id)
        self.request.user.watched_films.remove(film)
        self.request.user.save()
        return super(RemoveFromWatched, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('films:film-view', kwargs={'movie_id': self.kwargs['movie_id']})


class RemoveFromFavs(RedirectView):
    def get(self, request, *args, **kwargs):
        movie_id = self.kwargs['movie_id']
        film = Film.objects.get(imdbId=movie_id)
        self.request.user.fav_list.remove(film)
        self.request.user.save()
        return super(RemoveFromFavs, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('films:film-view', kwargs={'movie_id': self.kwargs['movie_id']})


class ProfileView(DetailView):
    template_name = 'accounts/profile.html'

    def get_object(self, queryset=None):
        user = User.objects.get(username=self.request.user.username)
        return user


class PageView(DetailView):
    template_name = 'accounts/page.html'

    def get_object(self, queryset=None):
        user = User.objects.get(username=self.kwargs['username'])
        return user


class EditProfileView(FormMixin, DetailView):
    template_name = 'accounts/edit-profile.html'
    context_object_name = 'u'

    def get_context_data(self, **kwargs):
        # context = super(EditProfileView, self).get_context_data(**kwargs)
        context = dict()
        context[self.context_object_name] = self.get_object()
        return context

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name, self.get_context_data())


    def get_object(self, queryset=None):
        user = User.objects.get(username=self.request.user.username)
        return user

    def post(self, request, *args, **kwargs):
        user = self.request.user

        fullname = self.request.POST['name']
        bio      = self.request.POST['bio']
        try:
            avatar   = self.request.FILES['avatar']
        except MultiValueDictKeyError:
            avatar = user.avatar


        user.avatar = avatar
        user.name = fullname
        user.bio = bio
        user.save()

        return HttpResponseRedirect(reverse_lazy('accounts:profile'))


class FindPeopleView(FormMixin, ListView):
    template_name = 'accounts/find_people.html'

    def post(self, request, *args, **kwargs):
        query = self.request.POST['query']
        results = User.objects.filter(name__contains=query)
        return render(request, self.template_name, {'results': results})


class AddToRequested(RedirectView):

    def get(self, request, *args, **kwargs):
        requested_friend_username = self.kwargs['username']
        requested_friend = User.objects.get(username=requested_friend_username)
        user = User.objects.get(username=self.request.user.username)
        requested_friend.requested_users.add(user)
        requested_friend.save()
        return super(AddToRequested, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('accounts:user-page', kwargs={'username': self.kwargs['username']})


class NotificationView(FormMixin, ListView):
    template_name = 'accounts/notification-view.html'

    def get(self, request, *args, **kwargs):
        user = self.request.user
        results = user.requested_users.all()
        return render(request, self.template_name, {'results': results})


class AddToFriends(RedirectView):

    def get(self, request, *args, **kwargs):
        user = self.request.user
        friend_username = self.kwargs['username']
        friend = User.objects.get(username=friend_username)
        user.friends.add(friend)
        user.requested_users.remove(friend)
        user.save()
        return super(AddToFriends, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('accounts:notification')


class Reject(RedirectView):

    def get(self, request, *args, **kwargs):
        user = self.request.user
        friend_username = self.kwargs['username']
        friend = User.objects.get(username=friend_username)
        user.requested_users.remove(friend)
        user.save()
        return super(Reject, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('accounts:notification')


class CreateSuggestView(TemplateView):
    template_name = 'accounts/suggest.html'

    def get_context_data(self, **kwargs):
        context = super(CreateSuggestView, self).get_context_data(**kwargs)
        movie_id = self.kwargs['movie_id']
        film = Film.objects.get(imdbId=movie_id)
        context['film'] = film
        return context


    def get(self, request, *args, **kwargs):
        return super(CreateSuggestView, self).get(request, *args, **kwargs)


    def post(self, request, *args, **kwargs):



        return super(CreateSuggestView, self).get(request, *args, **kwargs)

accounts/templates/accounts/edit-profile.html
{% extends 'layout.html'%}
{% block title %}
Edit {{ u }}
{% endblock %}
{% block body %}

<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <div class="container bg-primary rounded">
        <div class="row">
            <div class="col">
                <p class="h1 text-center">@{{ u.username }}</p>
            </div>
        </div>
        <div class="row  pb-3">
            <div class="col-3 bg-secondary pb-3">
                <img class="img-fluid rounded-circle img-thumbnail" src="{{ u.avatar.url }}" >
                <input class="btn btn-light form-control-file" type="file" name="avatar" value="{{ u.avatar }}">
            </div>
            <div class="col-9 bg-dark p-3">
                <div class="form-group">
                    <label class="text-white" for="exampleInputEmail1">Full Name:</label>
                    <input type="text" class="form-control" id="fullname" name="name" value="{{ u.name }}"
                           aria-describedby="fullnameHelp" placeholder="Fullname">
                    <small id="fullnameHelp" class="form-text text-muted">It will display to others as your name.</small>
                </div>
                <div class="form-group">
                    <label class="text-white" for="exampleInputEmail1">Bio:</label>
                    <input type="text" class="form-control" id="fullname" name="bio" value="{{ u.bio }}"
                           aria-describedby="emailHelp" placeholder="How do you describe yourself?">
                    <small id="fullnameHelp" class="form-text text-muted">example: I'm a movie freak!</small>
                </div>
                <input class="btn btn-success float-right" type="submit" value="Save">
            </div>
        </div>
    </div>
</form>



{% endblock %}

accounts/templates/accounts/find_people.html
{% extends 'layout.html' %}
{% load user_detail %}
{% load static %}
{% block style %}
<meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Search in People</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
    .view-group {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: row;
    flex-direction: row;
    padding-left: 0;
    margin-bottom: 0;
}
.thumbnail
{
    margin-bottom: 30px;
    padding: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    border-radius: 0px;
}

.item.list-group-item
{
    float: none;
    width: 100%;
    background-color: #fff;
    margin-bottom: 30px;
    -ms-flex: 0 0 100%;
    flex: 0 0 100%;
    max-width: 100%;
    padding: 0 1rem;
    border: 0;
}
.item.list-group-item .img-event {
    float: left;
    width: 30%;
}

.item.list-group-item .list-group-image
{
    margin-right: 10px;
}
.item.list-group-item .thumbnail
{
    margin-bottom: 0px;
    display: inline-block;
}
.item.list-group-item .caption
{
    float: left;
    width: 70%;
    margin: 0;
}

.item.list-group-item:before, .item.list-group-item:after
{
    display: table;
    content: " ";
}

.item.list-group-item:after
{
    clear: both;
}    </style>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />');
            else $('head > link').filter(':first').replaceWith(defaultCSS);
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height());
          window.parent.postMessage( iframe_height, 'https://bootsnipp.com');
        });
    </script>
</head>
{% endblock %}
{% block body %}
<body>
    <div class="container">
{#    <div class="row">#}
{#        <div class="col-lg-12 my-3">#}
{#            <div class="pull-right">#}
{#                <div class="btn-group">#}
{#                    <button class="btn btn-info" id="list">#}
{#                        List View#}
{#                    </button>#}
{#                    <button class="btn btn-danger" id="grid">#}
{#                        Grid View#}
{#                    </button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <div id="products" class="row view-group">
        {% for u in results %}
                <div class="item col-xs-4 col-lg-4  bg-transparent">
                    <div class="thumbnail card bg-dark text-white">
                        <div class="img-event">
                            {% if u.avatar %}
                                <img class="group list-group-image rounded-circle" src="{{ u.avatar.url }}" alt="user avatar" width="100" height="100"/>
                            {% else %}
                                <img class="group list-group-image p-3" src={% static 'img/user.png' %} alt="user avatar" width="100" height="100"/>

                            {% endif %}
                        </div>
                        <div class="caption card-body">
                            <h4 class="group card-title inner list-group-item-heading">@{{ u.username }}</h4>
                            <p class="group inner list-group-item-text">
                                {{ u.name }}</p>
                            <div class="row">
                                <div class="col col-xs-12 col-md-1 align-self-center">
                                    <p class="badge badge-success" style="font-size: small">Last Watched:</p>
                                    <p class="badge badge-success" style="font-size: small">{{ u.last_watched_film.title }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-md-6">
                                    <a class="btn btn-success" href="{% url 'accounts:user-page' u.username %}">Go To Profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>
{#    <script type="text/javascript">#}
{#	$(document).ready(function() {#}
{#            $('#list').click(function(event){event.preventDefault();$('#products .item').addClass('list-group-item');});#}
{#            $('#grid').click(function(event){event.preventDefault();$('#products .item').removeClass('list-group-item');$('#products .item').addClass('grid-group-item');});#}
{#        });	</script>#}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% load bootstrap %}
{% block title %}
Login Page
{% endblock %}
{% block body %}
    <form action="" method="post">
    {{ form|bootstrap }}
        {% csrf_token %}
    <input class="btn btn-primary" type="submit" value="Log in">
    </form>
{%  endblock %}

accounts/templates/accounts/notification-view.html
{% extends 'layout.html' %}
{% load user_detail %}
{% load static %}
{% block style %}
<meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Notification</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
    .view-group {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: row;
    flex-direction: row;
    padding-left: 0;
    margin-bottom: 0;
}
.thumbnail
{
    margin-bottom: 30px;
    padding: 0px;
    -webkit-border-radius: 0px;
    -moz-border-radius: 0px;
    border-radius: 0px;
}

.item.list-group-item
{
    float: none;
    width: 100%;
    background-color: #fff;
    margin-bottom: 30px;
    -ms-flex: 0 0 100%;
    flex: 0 0 100%;
    max-width: 100%;
    padding: 0 1rem;
    border: 0;
}
.item.list-group-item .img-event {
    float: left;
    width: 30%;
}

.item.list-group-item .list-group-image
{
    margin-right: 10px;
}
.item.list-group-item .thumbnail
{
    margin-bottom: 0px;
    display: inline-block;
}
.item.list-group-item .caption
{
    float: left;
    width: 70%;
    margin: 0;
}

.item.list-group-item:before, .item.list-group-item:after
{
    display: table;
    content: " ";
}

.item.list-group-item:after
{
    clear: both;
}    </style>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />');
            else $('head > link').filter(':first').replaceWith(defaultCSS);
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height());
          window.parent.postMessage( iframe_height, 'https://bootsnipp.com');
        });
    </script>
</head>
{% endblock %}
{% block body %}

    <div class="container">

    <div id="products" class="row view-group">
        {% for u in results %}
            <div class="item col-xs-4 col-lg-4  bg-transparent">
                <div class="thumbnail card bg-dark text-white">
                    <div class="img-event">
                        {% if u.avatar %}
                            <img class="group list-group-image rounded-circle" src="{{ u.avatar.url }}" alt="user avatar" width="100" height="100"/>
                        {% else %}
                            <img class="group list-group-image p-3" src="{% static 'img/user.png' %}" alt="user avatar" width="100" height="100"/>
                        {% endif %}
                        </div>
                        <div class="caption card-body">
                            <h4 class="group card-title inner list-group-item-heading">@{{ u.username }}</h4>
                            <p class="group inner list-group-item-text">{{ u.name }}</p>
                            <div class="container">
                                <div class="row">
                                    <div class="col col-xs-12 col-md-1 p-0 m-0">
                                        <p class="badge badge-success" style="font-size: small">Last Watched:</p>
                                        <p class="badge badge-success" style="font-size: small">{{ u.last_watched_film.title }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 p-0 m-0">
                                        <a class="btn btn-outline-danger" href="{% url 'accounts:reject' u.username %}">Reject</a>
                                    </div>
                                    <div class="col-xs-12 p-0 ml-3">
                                        <a class="btn btn-outline-success" href="{% url 'accounts:add-to-friends' u.username %}">Accept</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/page.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% load user_detail %}
{% load static %}
{% block title %}
{{ u }} Page
{% endblock %}
{% block body %}
    <div class="container text-center">
    <p class="h1">{{ user.name }}</p>
    {% if u.avatar %}
        <img class="group list-group-image rounded-circle" src="{{ u.avatar.url }}" alt="user avatar" width="100" height="100"/>
    {% else %}
        <img class="group list-group-image p-3" src="{% static 'img/user.png' %}" alt="user avatar" width="100" height="100"/>
    {% endif %}

        <div class="row">
        <div class="col">
            <p class="badge btn-primary float-right">Username :</p>
        </div>
        <div class="col">
            <span class="badge badge-secondary ml-4 float-left">{{ user.username }}</span>
        </div>
    </div>
    <div class="row">
        <div class="col">
        <div class="badge btn-primary float-right">Watched Movies :</div>
        </div>
        <div class="col float-right text-left">
        {% for title in user.watched_films|list_of_movies %}
            <a href="{% url 'films:film-redirector' title %}">
            <span class="badge badge-secondary ml-4">
                 {{ title }}
            </span>
            </a>
        <br>
        {% endfor %}
        </div>
    </div>


    <div class="row">
        <div class="col">
        <div class="badge btn-primary float-right">Favorite Films :</div>
        </div>
        <div class="col float-right text-left">
        {% if user.fav_list|list_of_movies != '' %}
            {% for title in user.fav_list|list_of_movies %}
            <a href="{% url 'films:film-redirector' title %}">
            <span class="badge badge-secondary ml-4">
                {{ title }}
            </span>
            </a>
        <br>
        {% endfor %}

        {% else %}
        <span class="badge badge-secondary ml-4">
        Nothing! <a href="{% url 'films:search' %}"> Add? </a>
        </span>
        {% endif %}
        </div>
    </div>

    </div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% load user_detail %}
{% load static %}
{% block title %}
{{ user }} Profile
{% endblock %}
{% block body %}
    <div class="container text-center">
    <p class="h1">{{ user.name }}</p>
    {% if user.avatar %}
            <img class="group list-group-image rounded-circle" src="{{ user.avatar.url }}" alt="user avatar" width="100" height="100"/>
    {% else %}
            <img class="group list-group-image p-3" src="{% static 'img/user.png' %}" alt="user avatar" width="100" height="100"/>
    {% endif %}

        <hr>
        <div class="row">
        <div class="col">
            <p class="badge btn-primary float-right">Username :</p>
        </div>
        <div class="col">
            <span class="badge badge-secondary ml-4 float-left">{{ user.username }}</span>
        </div>
    </div>
    <div class="row">
        <div class="col">
        <div class="badge btn-primary float-right">Watched Movies :</div>
        </div>
        <div class="col float-right text-left">
        {% for title in user.watched_films|list_of_movies %}
            <a href="{% url 'films:film-redirector' title %}">
            <span class="badge badge-secondary ml-4">
                 {{ title }}
            </span>
            </a>
        <br>
        {% endfor %}
        </div>
    </div>


    <div class="row">
        <div class="col">
        <div class="badge btn-primary float-right">Favorite Films :</div>
        </div>
        <div class="col float-right text-left">
        {% if user.fav_list|list_of_movies != '' %}
            {% for title in user.fav_list|list_of_movies %}
            <a href="{% url 'films:film-redirector' title %}">
            <span class="badge badge-secondary ml-4">
                {{ title }}
            </span>
            </a>
        <br>
        {% endfor %}

        {% else %}
        <span class="badge badge-secondary ml-4">
        Nothing! <a href="{% url 'films:search' %}"> Add? </a>
        </span>
        {% endif %}
        </div>
    </div>
    <a class="btn btn-info mt-3" href="{% url 'accounts:user-edit' %}">Edit Profile</a>
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% load bootstrap %}
{% block title %}
SignUp Page
{% endblock %}
{% block body %}
    <form action="" method="post">
    {{ form|bootstrap }}
        {% csrf_token %}
    <input class="btn btn-primary" type="submit" value="Sign up">
    </form>
{%  endblock %}

accounts/templates/accounts/suggest.html
{% extends 'layout.html' %}
{% block title %}
    Suggest To Friends!
{% endblock %}
{% block body %}

<form action="" method="post">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <img src="{{ film.fullsize_poster }}" height="50%">
            </div>

        </div>




    <input type="submit">
    </div>
</form>


{% endblock %}